"""Alembic migration for the analytics tables.

Creates the tables the Spark analytics jobs write to. Written by hand rather
than autogenerated, because the schema is owned by the SQL files applied at
startup and Alembic version-controls forward changes on top of them.
"""
